// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Result mirrors httpexec.Result: a union the frontend can branch on without
 * parsing prose. Update is nil when the app is already up to date.
 */
export interface Result {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "update": Update | null;
}

/**
 * Update describes a release newer than the running one.
 */
export interface Update {
    "version": string;
    "notes": string;

    /**
     * CanSelfUpdate is false where the frontend must offer a manual download
     * instead of an install button.
     */
    "canSelfUpdate": boolean;
}
