// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the bound service. It is registered through application.NewService
 * so the bindings generator can see it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply installs what Download staged and ends the running process. Anything it
 * returns is a failure — on success the app is on its way out.
 */
export function Apply(): $CancellablePromise<$models.Result> {
    return $Call.ByID(4029120344);
}

/**
 * CanSelfUpdate reports whether Apply can do anything on this platform.
 */
export function CanSelfUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(22978625);
}

/**
 * Check asks the manifest whether anything newer exists. A nil Update with OK
 * means the app is current; that is the common case and the frontend shows
 * nothing for it.
 * 
 * ctx is first so the binding is context-aware and the call can be cancelled from
 * the frontend, the same rule httpexec.Send follows.
 */
export function Check(): $CancellablePromise<$models.Result> {
    return $Call.ByID(134952380);
}

/**
 * CurrentVersion reports the running version, so the frontend can show what it
 * would be upgrading from without trusting its own build-time constant.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1463162555);
}

/**
 * Download fetches and verifies the release found by Check, leaving it staged on
 * disk. It deliberately stops short of applying: the user is asked before
 * anything restarts.
 */
export function Download(): $CancellablePromise<$models.Result> {
    return $Call.ByID(3757999612);
}

/**
 * OpenDownloadPage opens the releases page in the user's browser. It is the only
 * path offered on Linux, and the fallback everywhere else when something fails.
 */
export function OpenDownloadPage(): $CancellablePromise<$models.Result> {
    return $Call.ByID(2704443927);
}
