version: '3'

includes:
  common: ./build/Taskfile.yml

vars:
  APP_NAME: HTTiny
  BIN_DIR: bin
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds HTTiny
    deps:
      - task: common:build:frontend
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} .

  run:
    summary: Builds and runs HTTiny
    deps: [build]
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}}

  dev:
    summary: Runs HTTiny with frontend hot reload
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

