import { backtick, double, multiline } from './quote'
import { bodyOf, fileOf, isTextBody, partsOf, snippetHeaders, type Wire } from './types'

/**
 * A body worth reading as a template literal, escaped as a string when it is one line.
 *
 * The template form is only reached for a multi-line payload, which is where it pays: a
 * formatted JSON body as a single `"{\n  \"a\": 1\n}"` is technically correct and
 * unreadable.
 */
const body = (wire: Wire): string => {
  const text = bodyOf(wire)
  return multiline(text) ? backtick(text) : double(text)
}

const headerLines = (wire: Wire, pad: string): string[] => {
  const headers = snippetHeaders(wire)
  if (!headers.length) return []
  return [`${pad}headers: {`, ...headers.map(header => `${pad}  ${double(header.key)}: ${double(header.value)},`), `${pad}},`]
}

/**
 * The `FormData` a multipart request needs, built before the call.
 *
 * `openAsBlob` is Node's own bridge from a path to something `FormData` accepts, and it
 * is what keeps this target dependency-free: `form-data` and `node-fetch` are the usual
 * answer and neither is needed on Node 20. In a browser this is the one part that cannot
 * be pasted as-is — a page has no filesystem, and the `File` would come from an input.
 *
 * The third argument to `append` is the filename, which is what ends up in the part's
 * `Content-Disposition`. Without it every attachment is called `blob`.
 */
const formLines = (wire: Wire): string[] => {
  const parts = partsOf(wire)
  if (!parts.length) return []
  // The import earns its place only when something is actually opened: a form of plain
  // text fields needs no filesystem, and an unused import is noise in a snippet whose
  // whole claim is that it needs no dependencies.
  const opens = parts.some(part => part.kind === 'file')
  const lines = [...(opens ? ["import { openAsBlob } from 'node:fs'", ''] : []), 'const form = new FormData()']
  for (const part of parts) {
    if (part.kind !== 'file') {
      lines.push(`form.append(${double(part.name)}, ${double(part.value)})`)
      continue
    }
    const options = part.contentType ? `, { type: ${double(part.contentType)} }` : ''
    lines.push(`form.append(${double(part.name)}, await openAsBlob(${double(part.path)}${options}), ${double(part.filename)})`)
  }
  return [...lines, '']
}

/** What goes in the `body`/`data` field, or null when there is nothing to send. */
const payload = (wire: Wire): string | null => {
  if (partsOf(wire).length) return 'form'
  const file = fileOf(wire)
  // No `{ type }` here: the Content-Type is already in the header map for a binary body
  // — it is not regenerated by a form builder — and an explicit header wins over a
  // Blob's own type in both fetch and axios.
  if (file) return `await openAsBlob(${double(file.path)})`
  return isTextBody(wire) ? body(wire) : null
}

const fileImport = (wire: Wire): string[] => (fileOf(wire) ? ["import { openAsBlob } from 'node:fs'", ''] : [])

/**
 * `fetch`, as written in a Node script or a devtools console.
 *
 * `AbortSignal.timeout` carries the app's timeout, which is the one policy fetch has no
 * option for. Redirects need nothing: following them is fetch's default, and its cap is
 * not configurable — 20 in Node, and this app's ten is the stricter of the two.
 *
 * Worth knowing where this will *not* behave like the app: run from a page, it is subject
 * to CORS and silently drops `User-Agent`, `Cookie`, `Host` and `Referer` as forbidden
 * header names. That gap is the whole reason requests are performed in Go here — see the
 * package comment in `internal/httpexec`.
 */
export const fetchSnippet = (wire: Wire): string => {
  const data = payload(wire)
  const lines = [...fileImport(wire), ...formLines(wire), `const response = await fetch(${double(wire.url)}, {`, `  method: ${double(wire.method)},`]
  lines.push(...headerLines(wire, '  '))
  if (data) lines.push(`  body: ${data},`)
  lines.push(`  signal: AbortSignal.timeout(${wire.policy.timeoutMs}),`, '})', '', 'console.log(await response.text())')
  return lines.join('\n')
}

/**
 * axios.
 *
 * `axios.request` rather than `axios.get`/`axios.post` so the method is data like every
 * other field, which is also what keeps a verb axios has no shorthand for working.
 * `maxRedirects` is spelled out because axios's default is 5 — fewer than this app's ten.
 */
export const axios = (wire: Wire): string => {
  const data = payload(wire)
  const lines = [
    ...fileImport(wire),
    ...formLines(wire),
    `const response = await axios.request({`,
    `  method: ${double(wire.method)},`,
    `  url: ${double(wire.url)},`,
  ]
  lines.push(...headerLines(wire, '  '))
  if (data) lines.push(`  data: ${data},`)
  lines.push(`  timeout: ${wire.policy.timeoutMs},`, `  maxRedirects: ${wire.policy.maxRedirects},`, '})', '', 'console.log(response.data)')
  return lines.join('\n')
}
