// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoadResult crosses the binding. Payload is the payload's JSON *text*; the
 * frontend parses and validates it.
 */
export interface LoadResult {
    "found": boolean;
    "version": number;
    "payload": string;

    /**
     * Set when an unreadable file was moved aside, so the UI can say where it went.
     */
    "quarantined": string;
}

/**
 * Secret is one request's credentials as they cross the binding.
 */
export interface Secret {
    "id": string;
    "token": string;
    "password": string;
}

/**
 * SecretsResult reports whether the credential store could be used at all, so the
 * UI can tell the user their tokens are session-only instead of silently losing
 * them. Failing to reach a keychain must never fail the workspace load.
 */
export interface SecretsResult {
    "available": boolean;
    "secrets": Secret[] | null;
    "error": string;
}
