// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportResult carries the file's text back for the frontend to validate.
 * 
 * Contents and not a path: the frontend owns the payload schema, so it is the only side
 * that can say whether these bytes are a workspace. Handing back a path instead would
 * mean Go reading a file it cannot judge, or the webview holding a path it cannot open.
 */
export interface ImportResult {
    "ok": boolean;
    "cancelled": boolean;
    "path": string;
    "contents": string;
    "errorCode": string;
    "errorText": string;
}

/**
 * LoadResult crosses the binding. Payload is the payload's JSON *text*; the
 * frontend parses and validates it.
 */
export interface LoadResult {
    "found": boolean;
    "version": number;
    "payload": string;

    /**
     * Set when an unreadable file was moved aside, so the UI can say where it went.
     */
    "quarantined": string;
}

/**
 * Secret is one request's credentials as they cross the binding.
 */
export interface Secret {
    "id": string;
    "token": string;
    "password": string;
}

/**
 * SecretsResult reports whether the credential store could be used at all, so the
 * UI can tell the user their tokens are session-only instead of silently losing
 * them. Failing to reach a keychain must never fail the workspace load.
 */
export interface SecretsResult {
    "available": boolean;
    "secrets": Secret[] | null;
    "error": string;
}

/**
 * TransferResult reports an export.
 * 
 * Cancelled is its own field rather than an error code, for the reason httpexec's
 * SaveResult gives: dismissing a file dialog is the most ordinary thing a person can do
 * with one, and the interface must not be able to render it as a failure.
 */
export interface TransferResult {
    "ok": boolean;
    "cancelled": boolean;

    /**
     * Where it was written, so the UI can name the file it just produced.
     */
    "path": string;
    "errorCode": string;
    "errorText": string;
}
