// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DataDir lets the UI tell the user where their collections actually live.
 */
export function DataDir(): $CancellablePromise<string> {
    return $Call.ByID(875064860);
}

/**
 * ExportFile writes an already-serialised workspace export to a file the user chooses.
 * 
 * The dialog is opened here rather than from the frontend, although the Wails runtime
 * offers both — the reason httpexec's SaveBody gives: going the other way means handing
 * a filesystem path back across the binding for Go to write to, which is a wider door
 * than this needs.
 * 
 * Contents arrives serialised because the frontend owns the payload schema. Go neither
 * builds nor validates it, exactly as it does not for workspace.json.
 */
export function ExportFile(contents: string, filename: string, title: string): $CancellablePromise<$models.TransferResult> {
    return $Call.ByID(1539235637, contents, filename, title);
}

/**
 * ImportFile opens a workspace export the user chooses and hands back its text.
 */
export function ImportFile(title: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3755610682, title);
}

export function LoadPrefs(): $CancellablePromise<$models.LoadResult> {
    return $Call.ByID(4024617645);
}

/**
 * LoadSecrets fetches credentials for the given request ids in one call rather than
 * one round trip each, which matters because this sits on the startup path.
 * 
 * The reads run concurrently but are assembled in the caller's order, and the last error
 * in that order still wins — the same answer the sequential loop gave, so nothing
 * downstream can tell the difference.
 */
export function LoadSecrets(ids: string[] | null): $CancellablePromise<$models.SecretsResult> {
    return $Call.ByID(1489042866, ids);
}

export function LoadWorkspace(): $CancellablePromise<$models.LoadResult> {
    return $Call.ByID(939686834);
}

export function SavePrefs(payload: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(2125053962, payload, version);
}

/**
 * SaveSecrets writes the given credentials and removes every stored entry whose id
 * is not in `keep`, so deleting a request or clearing its token also clears the
 * keychain. `keep` is the full set of live request ids.
 */
export function SaveSecrets(entries: $models.Secret[] | null, keep: string[] | null): $CancellablePromise<$models.SecretsResult> {
    return $Call.ByID(1517057117, entries, keep);
}

export function SaveWorkspace(payload: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(337654957, payload, version);
}
