// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DataDir lets the UI tell the user where their collections actually live.
 */
export function DataDir(): $CancellablePromise<string> {
    return $Call.ByID(685828284);
}

export function LoadPrefs(): $CancellablePromise<$models.LoadResult> {
    return $Call.ByID(3659111629);
}

/**
 * LoadSecrets fetches credentials for the given request ids in one call rather than
 * one round trip each, which matters because this sits on the startup path.
 */
export function LoadSecrets(ids: string[] | null): $CancellablePromise<$models.SecretsResult> {
    return $Call.ByID(3603143122, ids);
}

export function LoadWorkspace(): $CancellablePromise<$models.LoadResult> {
    return $Call.ByID(3873956306);
}

export function SavePrefs(payload: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(1057156010, payload, version);
}

/**
 * SaveSecrets writes the given credentials and removes every stored entry whose id
 * is not in `keep`, so deleting a request or clearing its token also clears the
 * keychain. `keep` is the full set of live request ids.
 */
export function SaveSecrets(entries: $models.Secret[] | null, keep: string[] | null): $CancellablePromise<$models.SecretsResult> {
    return $Call.ByID(67004157, entries, keep);
}

export function SaveWorkspace(payload: string, version: number): $CancellablePromise<void> {
    return $Call.ByID(832011597, payload, version);
}
