// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Release lets the frontend drop a retained body when its tab closes or its response
 * is cleared. Nothing breaks if it is never called — the store has its own ceiling —
 * but a user who has just closed a tab has no reason to still be holding 30 MB of it.
 */
export function Release(id: string): $CancellablePromise<void> {
    return $Call.ByID(4284804684, id);
}

/**
 * SaveBody writes a response body to a file the user chooses.
 * 
 * This exists because the byte route made the app a dead end for its own best
 * output. A PDF, a PNG or a zip renders beautifully and cannot be got out: the copy
 * button is disabled for a body that is not text, and the bytes live only in this
 * process, under a 64 MiB ceiling that evicts them as soon as another large response
 * arrives.
 * 
 * The dialog is opened here rather than from the frontend, although the Wails
 * runtime offers both. The process that opens it is already the one holding the
 * bytes; going the other way would mean handing a filesystem path back across the
 * binding for Go to write to, which is a wider door than this needs.
 */
export function SaveBody(req: $models.SaveRequest): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(371893958, req);
}

/**
 * Send performs one request and reports the outcome.
 * 
 * ctx is the first parameter so that Wails marks the method as context-aware:
 * cancelling the CancellablePromise on the JS side cancels this context, which
 * aborts the connection rather than merely detaching the UI from it.
 */
export function Send(req: $models.Request): $CancellablePromise<$models.Result> {
    return $Call.ByID(2288105761, req);
}

/**
 * Wire reports the request Send would perform, without performing it.
 * 
 * Deliberately not context-aware — it does no I/O, so there is nothing to cancel and no
 * reason to hand the frontend a CancellablePromise.
 * 
 * The fidelity comes from *reading fields back off the built request* rather than
 * deriving them a second time: this is the same object, produced by the same code, that
 * a Send would hand to the transport.
 */
export function Wire(req: $models.Request): $CancellablePromise<$models.WireResult> {
    return $Call.ByID(734947098, req);
}
