// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Release lets the frontend drop a retained body when its tab closes or its response
 * is cleared. Nothing breaks if it is never called — the store has its own ceiling —
 * but a user who has just closed a tab has no reason to still be holding 30 MB of it.
 */
export function Release(id: string): $CancellablePromise<void> {
    return $Call.ByID(4284804684, id);
}

/**
 * Send performs one request and reports the outcome.
 * 
 * ctx is the first parameter so that Wails marks the method as context-aware:
 * cancelling the CancellablePromise on the JS side cancels this context, which
 * aborts the connection rather than merely detaching the UI from it.
 */
export function Send(req: $models.Request): $CancellablePromise<$models.Result> {
    return $Call.ByID(2288105761, req);
}
