// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveEntry is one file inside an archive. Sizes are the two that matter when
 * looking at a response: what it takes on the wire and what it becomes.
 */
export interface ArchiveEntry {
    "name": string;

    /**
     * Uncompressed size in bytes.
     */
    "size": number;

    /**
     * Size within the archive. Equal to Size for a stored entry.
     */
    "compressedSize": number;

    /**
     * RFC 3339, or empty when the entry carries no usable timestamp.
     */
    "modified": string;
    "directory": boolean;
}

export interface Auth {
    /**
     * none | bearer | basic
     */
    "type": string;
    "token": string;
    "username": string;
    "password": string;
}

/**
 * KeyValue is a header pair. The frontend's KeyValueRow carries `enabled`, `id`
 * and `description` too; those are editor concerns and are resolved away before
 * the request crosses the binding.
 */
export interface KeyValue {
    "key": string;
    "value": string;
}

/**
 * Request mirrors the frontend's RequestDocument minus everything the network does
 * not care about. `params` is deliberately absent: store.replaceQuery keeps the
 * query string inside `url`, so sending the rows as well would double-encode them.
 */
export interface Request {
    /**
     * Identifies the request whose bytes are being held, so a byte-backed response
     * can be found again on the asset route. It is the frontend's request id, and it
     * is only ever used as a map key — see bodystore.go.
     */
    "id": string;
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;

    /**
     * none | json | text
     */
    "bodyType": string;
    "body": string;
    "auth": Auth;

    /**
     * Overrides the default timeout when positive.
     */
    "timeoutMs": number;
}

export interface Response {
    "status": number;
    "statusText": string;
    "timeMs": number;
    "sizeBytes": number;
    "headers": KeyValue[] | null;

    /**
     * The payload, for textual formats only. Empty for every byte-backed format,
     * which carries BodyURL instead.
     */
    "body": string;

    /**
     * Where the webview can fetch a byte-backed payload. Empty for textual formats
     * and for a response with no body at all. The URL changes on every send, so an
     * <img> or <video> pointed at it always shows the current response.
     */
    "bodyUrl": string;

    /**
     * Bare media type, lowercased, parameters stripped.
     */
    "contentType": string;

    /**
     * The charset the payload was transcoded *from*, when it was not already UTF-8.
     * Empty means no transcoding happened.
     */
    "encoding": string;

    /**
     * The Content-Encoding found on the response, whether or not it could be undone.
     * Non-empty with a readable body means it was decompressed here; non-empty with a
     * binary one means the algorithm is not supported.
     */
    "contentEncoding": string;

    /**
     * Where the request ended up after redirects, which are otherwise invisible.
     */
    "finalUrl": string;

    /**
     * The entries of a zip response. Empty for every other format, and for an archive
     * whose index could not be read.
     */
    "archive": ArchiveEntry[] | null;

    /**
     * see classify.go
     */
    "format": string;
    "truncated": boolean;
}

/**
 * Result is an explicit success/failure union rather than a Go `error` return.
 * 
 * The frontend needs a stable machine-readable code, and marshalling a Go error
 * across the binding yields a human string whose format is not part of any
 * contract. Returning the code as data keeps the mapping in one place — the
 * `classify` function below — instead of splitting it across a stringly-typed
 * boundary.
 */
export interface Result {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "response": Response;
}
