// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Auth {
    /**
     * none | bearer | basic
     */
    "type": string;
    "token": string;
    "username": string;
    "password": string;
}

/**
 * KeyValue is a header pair. The frontend's KeyValueRow carries `enabled`, `id`
 * and `description` too; those are editor concerns and are resolved away before
 * the request crosses the binding.
 */
export interface KeyValue {
    "key": string;
    "value": string;
}

/**
 * Request mirrors the frontend's RequestDocument minus everything the network does
 * not care about. `params` is deliberately absent: store.replaceQuery keeps the
 * query string inside `url`, so sending the rows as well would double-encode them.
 */
export interface Request {
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;

    /**
     * none | json | text
     */
    "bodyType": string;
    "body": string;
    "auth": Auth;

    /**
     * Overrides the default timeout when positive.
     */
    "timeoutMs": number;
}

export interface Response {
    "status": number;
    "statusText": string;
    "timeMs": number;
    "sizeBytes": number;
    "headers": KeyValue[] | null;

    /**
     * Empty when Format is "binary".
     */
    "body": string;

    /**
     * Bare media type, lowercased, parameters stripped.
     */
    "contentType": string;

    /**
     * json | html | xml | text | binary
     */
    "format": string;
    "truncated": boolean;
}

/**
 * Result is an explicit success/failure union rather than a Go `error` return.
 * 
 * The frontend needs a stable machine-readable code, and marshalling a Go error
 * across the binding yields a human string whose format is not part of any
 * contract. Returning the code as data keeps the mapping in one place — the
 * `classify` function below — instead of splitting it across a stringly-typed
 * boundary.
 */
export interface Result {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "response": Response;
}
