// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveEntry is one file inside an archive. Sizes are the two that matter when
 * looking at a response: what it takes on the wire and what it becomes.
 */
export interface ArchiveEntry {
    "name": string;

    /**
     * Uncompressed size in bytes.
     */
    "size": number;

    /**
     * Size within the archive. Equal to Size for a stored entry.
     */
    "compressedSize": number;

    /**
     * RFC 3339, or empty when the entry carries no usable timestamp.
     */
    "modified": string;
    "directory": boolean;
}

export interface Auth {
    /**
     * none | bearer | basic
     */
    "type": string;
    "token": string;
    "username": string;
    "password": string;
}

/**
 * KeyValue is a header pair. The frontend's KeyValueRow carries `enabled`, `id`
 * and `description` too; those are editor concerns and are resolved away before
 * the request crosses the binding.
 */
export interface KeyValue {
    "key": string;
    "value": string;
}

/**
 * Request mirrors the frontend's RequestDocument minus everything the network does
 * not care about. `params` is deliberately absent: store.replaceQuery keeps the
 * query string inside `url`, so sending the rows as well would double-encode them.
 */
export interface Request {
    /**
     * Identifies the request whose bytes are being held, so a byte-backed response
     * can be found again on the asset route. It is the frontend's request id, and it
     * is only ever used as a map key — see bodystore.go.
     */
    "id": string;
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;

    /**
     * none | json | text
     */
    "bodyType": string;
    "body": string;
    "auth": Auth;

    /**
     * Overrides the default timeout when positive.
     */
    "timeoutMs": number;
}

export interface Response {
    "status": number;
    "statusText": string;
    "timeMs": number;
    "sizeBytes": number;
    "headers": KeyValue[] | null;

    /**
     * The payload, for textual formats only. Empty for every byte-backed format,
     * which carries BodyURL instead.
     */
    "body": string;

    /**
     * Where the webview can fetch a byte-backed payload. Empty for textual formats
     * and for a response with no body at all. The URL changes on every send, so an
     * <img> or <video> pointed at it always shows the current response.
     */
    "bodyUrl": string;

    /**
     * Bare media type, lowercased, parameters stripped.
     */
    "contentType": string;

    /**
     * The charset the payload was transcoded *from*, when it was not already UTF-8.
     * Empty means no transcoding happened.
     */
    "encoding": string;

    /**
     * The Content-Encoding found on the response, whether or not it could be undone.
     * Non-empty with a readable body means it was decompressed here; non-empty with a
     * binary one means the algorithm is not supported.
     */
    "contentEncoding": string;

    /**
     * Where the request ended up after redirects, which are otherwise invisible.
     */
    "finalUrl": string;

    /**
     * The entries of a zip response. Empty for every other format, and for an archive
     * whose index could not be read.
     */
    "archive": ArchiveEntry[] | null;

    /**
     * see classify.go
     */
    "format": string;
    "truncated": boolean;
}

/**
 * Result is an explicit success/failure union rather than a Go `error` return.
 * 
 * The frontend needs a stable machine-readable code, and marshalling a Go error
 * across the binding yields a human string whose format is not part of any
 * contract. Returning the code as data keeps the mapping in one place — the
 * `classify` function below — instead of splitting it across a stringly-typed
 * boundary.
 */
export interface Result {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "response": Response;
}

export interface WireHeader {
    "key": string;
    "value": string;

    /**
     * One of the source constants above. Cosmetic: the header list itself is read off
     * the real *http.Request, so a mislabelled row still reports what is actually sent.
     */
    "source": string;
}

/**
 * WirePolicy is what the client does that no request line shows — and what a generated
 * snippet has to opt into by hand to behave like this app does. Every field is read
 * from the constants Send uses, never restated as a literal.
 */
export interface WirePolicy {
    "timeoutMs": number;
    "maxRedirects": number;
    "http2": boolean;

    /**
     * Whether the transport will negotiate and transparently undo gzip. False as soon
     * as the user sets Accept-Encoding by hand, which is exactly when it stops being
     * transparent — see decompress.
     */
    "gzip": boolean;
    "verifyTls": boolean;
    "maxBodyBytes": number;
    "maxTextBytes": number;
}

/**
 * WireRequest is the request as it will leave this process.
 */
export interface WireRequest {
    "method": string;

    /**
     * Absolute, and already percent-encoded by parseTarget — so this is where a URL
     * typed with a literal space visibly becomes one with %20.
     */
    "url": string;

    /**
     * Path and query only, which is what goes in the request-line.
     */
    "target": string;

    /**
     * The Host header, whether it came from the URL or from an override row.
     */
    "host": string;

    /**
     * Whether Host came from a header row rather than from the URL. It is not in
     * Headers because applyHeaders diverts it to http.Request.Host — net/http reads
     * the field and ignores the map — so without this flag an override would be
     * invisible in every snippet.
     */
    "hostOverride": boolean;
    "headers": WireHeader[] | null;
    "body": string;
    "hasBody": boolean;
    "policy": WirePolicy;
}

/**
 * WireResult is a success/failure union for the same reason Result is one: the frontend
 * needs a stable code, and an invalid URL has to reach the code view as INVALID_URL
 * rather than as a half-built snippet.
 */
export interface WireResult {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "request": WireRequest;
}
