// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveEntry is one file inside an archive. Sizes are the two that matter when
 * looking at a response: what it takes on the wire and what it becomes.
 */
export interface ArchiveEntry {
    "name": string;

    /**
     * Uncompressed size in bytes.
     */
    "size": number;

    /**
     * Size within the archive. Equal to Size for a stored entry.
     */
    "compressedSize": number;

    /**
     * RFC 3339, or empty when the entry carries no usable timestamp.
     */
    "modified": string;
    "directory": boolean;
}

export interface Auth {
    /**
     * none | bearer | basic
     */
    "type": string;
    "token": string;
    "username": string;
    "password": string;
}

/**
 * Hop is one redirect that was followed. The chain is otherwise invisible: the app
 * follows redirects silently and only reports where it ended up.
 */
export interface Hop {
    "status": number;

    /**
     * The URL that answered with this redirect.
     */
    "url": string;

    /**
     * Where it pointed, verbatim from the Location header — so a relative one shows as
     * relative, which is what the server actually sent.
     */
    "location": string;

    /**
     * The method used for this hop. A 302 turns a POST into a GET, and seeing that is
     * most of the value of a chain.
     */
    "method": string;
    "ms": number;
}

/**
 * KeyValue is a header pair. The frontend's KeyValueRow carries `enabled`, `id`
 * and `description` too; those are editor concerns and are resolved away before
 * the request crosses the binding.
 */
export interface KeyValue {
    "key": string;
    "value": string;
}

/**
 * Phase is one segment of the waterfall: where it starts and how long it lasts, both
 * in milliseconds from the moment the send began.
 * 
 * An offset rather than a bare duration, because five durations side by side say
 * nothing about what happened when. With offsets the five read as one timeline, and
 * a gap between two of them is itself information.
 * 
 * Ms == 0 means the phase did not happen. That is not a fudge: a reused connection
 * genuinely has no DNS, no TCP and no TLS, and Timings.Reused is what explains it.
 */
export interface Phase {
    "at": number;
    "ms": number;
}

/**
 * Request mirrors the frontend's RequestDocument minus everything the network does
 * not care about. `params` is deliberately absent: store.replaceQuery keeps the
 * query string inside `url`, so sending the rows as well would double-encode them.
 */
export interface Request {
    /**
     * Identifies the request whose bytes are being held, so a byte-backed response
     * can be found again on the asset route. It is the frontend's request id, and it
     * is only ever used as a map key — see bodystore.go.
     */
    "id": string;
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;

    /**
     * none | json | text
     */
    "bodyType": string;
    "body": string;
    "auth": Auth;

    /**
     * Overrides the default timeout when positive.
     */
    "timeoutMs": number;
}

export interface Response {
    "status": number;
    "statusText": string;
    "timeMs": number;
    "sizeBytes": number;
    "headers": KeyValue[] | null;

    /**
     * The payload, for textual formats only. Empty for every byte-backed format,
     * which carries BodyURL instead.
     */
    "body": string;

    /**
     * Where the webview can fetch a byte-backed payload. Empty for textual formats
     * and for a response with no body at all. The URL changes on every send, so an
     * <img> or <video> pointed at it always shows the current response.
     */
    "bodyUrl": string;

    /**
     * Bare media type, lowercased, parameters stripped.
     */
    "contentType": string;

    /**
     * The charset the payload was transcoded *from*, when it was not already UTF-8.
     * Empty means no transcoding happened.
     */
    "encoding": string;

    /**
     * The Content-Encoding found on the response, whether or not it could be undone.
     * Non-empty with a readable body means it was decompressed here; non-empty with a
     * binary one means the algorithm is not supported.
     */
    "contentEncoding": string;

    /**
     * Where the request ended up after redirects, which are otherwise invisible.
     */
    "finalUrl": string;

    /**
     * What to call this body if it is saved. Read from the server's
     * Content-Disposition where there is one, else derived from the URL and the
     * format. Computed here because parsing that header correctly — including the
     * RFC 2231 encoded form — is `mime`'s job, not the viewer's.
     */
    "filename": string;

    /**
     * The entries of a zip response. Empty for every other format, and for an archive
     * whose index could not be read.
     */
    "archive": ArchiveEntry[] | null;

    /**
     * Where the time went, as a waterfall. See trace.go.
     */
    "timings": Timings;

    /**
     * The connection the final response arrived on. Nil for http://.
     */
    "tls": TLSInfo | null;

    /**
     * see classify.go
     */
    "format": string;
    "truncated": boolean;
}

/**
 * Result is an explicit success/failure union rather than a Go `error` return.
 * 
 * The frontend needs a stable machine-readable code, and marshalling a Go error
 * across the binding yields a human string whose format is not part of any
 * contract. Returning the code as data keeps the mapping in one place — the
 * `classify` function below — instead of splitting it across a stringly-typed
 * boundary.
 */
export interface Result {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "response": Response;

    /**
     * The redirects that were followed, oldest first, and empty when there were none.
     * 
     * Here rather than on Response, which is where it used to live, because the chain is
     * a property of the *exchange* and not of whatever answered last. On Response it was
     * unreachable from every failure — a chain abandoned for being too long, or one whose
     * next hop timed out, was discarded at exactly the moment it was most worth reading.
     * One home on the union means neither branch can forget it.
     */
    "redirects": Hop[] | null;
}

/**
 * SaveRequest asks for a response body to be written to a file the user picks.
 */
export interface SaveRequest {
    /**
     * The request whose body to save. Byte-backed payloads are found in the store
     * under this key; see bodystore.go.
     */
    "id": string;

    /**
     * The body as the viewer has it. Used only when the store holds nothing for ID —
     * a textual payload crossed the binding as a string and is deliberately not
     * retained here, so the frontend is the only place it still exists.
     */
    "text": string;

    /**
     * Suggested name, normally Response.Filename handed straight back. Sanitised
     * again on arrival rather than trusted: it made a round trip through the
     * frontend, and this is the side that puts it in front of a file dialog.
     */
    "filename": string;

    /**
     * The dialog's title. It comes from the frontend because it is translated copy
     * and the catalogue lives there; Go has no way to read it.
     */
    "title": string;
}

/**
 * SaveResult reports what happened.
 * 
 * Cancelled is its own field rather than an error code, and that is the whole point
 * of the shape: dismissing a file dialog is the most ordinary thing a person can do
 * with one, and the interface must not be able to render it as a failure.
 */
export interface SaveResult {
    "ok": boolean;
    "cancelled": boolean;

    /**
     * Where it was written, so the UI can name the file it just produced.
     */
    "path": string;
    "errorCode": string;
    "errorText": string;
}

/**
 * TLSInfo describes the connection the final response arrived on. Nil for http://.
 */
export interface TLSInfo {
    "version": string;
    "cipherSuite": string;

    /**
     * The protocol ALPN settled on — "h2" or "http/1.1". Empty if none was negotiated.
     */
    "alpn": string;

    /**
     * The handshake was skipped by resuming an earlier session, which is the TLS-level
     * twin of Reused above and explains a suspiciously quick negotiation.
     */
    "resumed": boolean;
    "serverName": string;

    /**
     * The leaf certificate. Empty when the peer sent none, which cannot happen for a
     * client but is cheap to be safe about.
     */
    "subject": string;
    "issuer": string;
    "notBefore": string;
    "notAfter": string;
    "dnsNames": string[] | null;
}

/**
 * Timings is where the time went.
 * 
 * The five phases partition the total rather than overlapping, which is why TTFB here
 * means the gap between the connection being ready and the first byte arriving —
 * the server's own thinking time — and not the conventional "everything up to the
 * first byte". It is what Chrome's waterfall labels "Waiting (TTFB)" for the same
 * reason.
 */
export interface Timings {
    "dns": Phase;
    "connect": Phase;
    "tls": Phase;
    "ttfb": Phase;
    "download": Phase;
    "totalMs": number;

    /**
     * The connection came from the idle pool, so nothing was resolved, dialled or
     * negotiated. The transport keeps 4 idle connections per host, which makes this
     * the ordinary case for a second send to the same place — and three empty bars
     * with no explanation read as a bug rather than as a fast request.
     */
    "reused": boolean;
}

export interface WireHeader {
    "key": string;
    "value": string;

    /**
     * One of the source constants above. Cosmetic: the header list itself is read off
     * the real *http.Request, so a mislabelled row still reports what is actually sent.
     */
    "source": string;
}

/**
 * WirePolicy is what a generated snippet has to opt into by hand to behave like this app
 * does. Every field is read from the constants Send uses, never restated as a literal,
 * and every field has a reader in frontend/src/snippets.
 * 
 * It carried four more, printed as a caption under the snippet, and all four are gone
 * with it. `http2` and `verifyTls` were literal `true`s — a field with only one possible
 * value describes nothing. `maxBodyBytes` and `maxTextBytes` are real limits, but they
 * are limits on the *response*, which is not what a code view is looking at; the response
 * panel says so where it actually bites.
 */
export interface WirePolicy {
    "timeoutMs": number;
    "maxRedirects": number;

    /**
     * Whether the transport will negotiate and transparently undo gzip. False as soon
     * as the user sets Accept-Encoding by hand, which is exactly when it stops being
     * transparent — see decompress.
     */
    "gzip": boolean;
}

/**
 * WireRequest is the request as it will leave this process.
 */
export interface WireRequest {
    "method": string;

    /**
     * Absolute, and already percent-encoded by parseTarget — so this is where a URL
     * typed with a literal space visibly becomes one with %20.
     */
    "url": string;

    /**
     * Path and query only, which is what goes in the request-line.
     */
    "target": string;

    /**
     * The Host header, whether it came from the URL or from an override row.
     */
    "host": string;

    /**
     * Whether Host came from a header row rather than from the URL. It is not in
     * Headers because applyHeaders diverts it to http.Request.Host — net/http reads
     * the field and ignores the map — so without this flag an override would be
     * invisible in every snippet.
     */
    "hostOverride": boolean;
    "headers": WireHeader[] | null;
    "body": string;
    "hasBody": boolean;
    "policy": WirePolicy;
}

/**
 * WireResult is a success/failure union for the same reason Result is one: the frontend
 * needs a stable code, and an invalid URL has to reach the code view as INVALID_URL
 * rather than as a half-built snippet.
 */
export interface WireResult {
    "ok": boolean;
    "errorCode": string;
    "errorText": string;
    "request": WireRequest;
}
